#Site Settings
name: Parohia Antim Ivireanul
title: Biserica Ortodoxa Sfantul Martir Antim Ivireanul
email: parohiaantim@gmail.com
description: Biserica parohială a comunităţii ortodoxe Sfântul Antim Ivireanul din Cergy-Pontoise, care se află în apropiere, a fost cumpărată de la Dioceza catolică, aceasta din urmă acceptând propunerea Mitropoliei româneşti cu sediul în apropierea Parisului.
timezone: Europe/Paris
author: Preot Paroh Lilian Mantaluta
author_email: preotlilianmantaluta@yahoo.fr
url: https://antimivireanul.ml
permalink: pretty
paginate: 3
paginate_path: "/blog/page:num/"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-103019958-1
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: preotlilianmantaluta@yahoo.fr
  facebook: antimivireanul.parohia
  flickr:
  github: antimivireanul
  instagram:
  linkedin:
  pinterest:
  rss: RSS
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: parohiaantim

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
- CNAME

theme: jekyll-theme-cayman
